### ISSUE TITLE
Lattepanda Support?

### ISSUE THREAD

**Issue by raymonable** [PDModdingCommunity/PD-Loader#11]
Does this work with the Lattepanda devices? If so, which, and what settings should I use for it?

**Comment by nastys** [comment]
You'd need to use a supported NVIDIA GPU with an eGPU adapter if 3D is to be rendered.

**Comment by raymonable** [comment]
how would you plug a gpu into an sbc

**Comment by raymonable** [comment]
never mind

**Comment by fuckmeinthetoiletuntilislurpyourcum** [comment]
Why does it say keychip not found?

**Comment by fuckmeinthetoiletuntilislurpyourcum** [comment]
ketchup?
