### ISSUE TITLE
White screen then it crashes

### ISSUE THREAD

**Issue by johnnyguitar12** [PDModdingCommunity/PD-Loader#13]
I open it up and it just goes to a white screen then closes no matter the settings. I'm on a AMD GPU if that helps.

**Comment by nastys** [comment]
Newer AMD drivers on Windows are not supported.
For troubleshooting, see: https://github.com/PDModdingCommunity/PD-Loader/wiki/3)-Usage,-Modules-(Costumes),-Troubleshooting#the-game-crashes-immediately--white-screen

**Comment by johnnyguitar12** [comment]
Oh I see, when are you planning on supporting new drivers?

**Comment by johnnyguitar12** [comment]
Thanks for the quick response by the way

**Comment by nastys** [comment]
> Oh I see, when are you planning on supporting new drivers?

Never. It's just like Intel or Mesa now, so there's no simple way to patch the game to make it work like with the old AMD drivers.

**Comment by johnnyguitar12** [comment]
How do you download the old drivers?

**Comment by nastys** [comment]
[Here](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-6-1) or [here](https://www.amd.com/en/support/kb/release-notes/rn-rad-win-22-6-1-legacy), depending on your GPU.

**Comment by johnnyguitar12** [comment]
Thanks
