### ISSUE TITLE
mfplat.dll link in install guide is dead

### ISSUE THREAD

**Issue by ethanaobrien** [PDModdingCommunity/PD-Loader#19]
Not looking to use it, just wanted to let the project maintainers know that the link is dead on [this page](https://github.com/PDModdingCommunity/PD-Loader/wiki/2%29+Installation)

https://cdn.discordapp.com/attachments/531655613969727501/609146259227541572/wmvdecod_6.1.7850.7z returns "This content is no longer available."

(Sorry for originally posting with no content, did not know pressing enter when focused on the title would open the issue with no body)

Edit: The divasound link also appears to be dead (https://cdn.discordapp.com/attachments/613450757227937792/895388022063910912/DivaSound_downgrade.7z)

**Comment by nastys** [comment]
Fixed
